[project]
name = "ctxmate-schema"
version = "0.0.2"
description = "Generated Protobuf types for ctxmate"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "protobuf~=6.30.2",
    "types-protobuf~=6.30.2"
]
